# Generated by Django 2.1.7 on 2019-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('avg_score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('rank', models.DecimalField(decimal_places=6, max_digits=10)),
                ('z_score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('scaled_score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('scaled_rank', models.DecimalField(decimal_places=6, max_digits=10)),
                ('scaled_z', models.DecimalField(decimal_places=6, max_digits=10)),
                ('isef_score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('isef_rank', models.DecimalField(decimal_places=6, max_digits=10)),
                ('no_show', models.BooleanField()),
            ],
        ),
    ]
